[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "yagso"
version = "0.1.1"
description = "CLI tool that manages Git submodule hierarchies via a YAML manifest"
authors = [{name = "Freddy Boutin", email = "didifred.web@gmail.com"}]
requires-python = ">=3.8"
dependencies = [
    "gitpython>=3.1.0",
    "pyyaml>=6.0",
    "rich>=13.7.0"
]

[project.scripts]
yagso = "yagso.cli.__main__:main"

[project.optional-dependencies]
dev = [
    "pytest",
    "coverage",
    "pygount",
    "deadcode"
]

[tool.setuptools.packages.find]
include = ["yagso*"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-v"

[tool.autopep8]
max_line_length = 100
aggressive = 2